### ISSUE TITLE
Preprint using PyG Temporal but not citing the paper.

### ISSUE THREAD

**Issue by benedekrozemberczki** [qcri/PDNS-Net#1]
As I understand you used PyG Temporal in your research but you did not cite the paper, why is that?

**Comment by ThatUdeshUK** [comment]
@benedekrozemberczki preprint published is an older version and didn't utilize the PyTorch Geometric Temporal. We will give appropriate credits on the updated version. Appreciate your work on PyTorch Geometric Temporal. Thank you.
